#!/usr/bin/env bash
# Write a Bash script that displays all active IPv4 IPs on the machine it’s executed on.
# Get all IPv4 addresses using ifconfig
ip -o addr | awk '!/^[0-9]*: ?lo|link\/ether/ {print $2" "$4}'